### PR TITLE
Fix broken --output argument

### PR DESCRIPTION
**Pull request by cormacpayne**

### CODE REVIEW

**Review by daniv-msft — APPROVED** [review]

**Comment by daniv-msft** [comment]
@demyte We're looking into this. Sorry about that. We're getting back to you shortly.

**Comment by cormacpayne** [comment]
@demyte Hey James, sorry about this break -- I'll fix it ASAP

**Comment by daniv-msft** [comment]
@demyte Here is the PR fixing this: https://github.com/Azure/container-apps-deploy-action/pull/67
We'll merge it and release it soon.

**Comment by cormacpayne** [comment]
@demyte Hey James, the PR has been merged and `v1` has been retagged to include this change -- would you mind giving it another shot and seeing if the issue has been resolved?

**Pull request merged**
